x-open-swe-build: &openswe-build
  context: .
  dockerfile: Dockerfile

services:
  agent:
    build: *openswe-build
    image: open-swe:local
    command: ["yarn", "workspace", "@openswe/agent", "dev"]
    ports:
      - "2024:2024"
    environment:
      OPEN_SWE_LOCAL_MODE: ${OPEN_SWE_LOCAL_MODE:-true}
      OPEN_SWE_LOCAL_PROJECT_PATH: ${OPEN_SWE_LOCAL_PROJECT_PATH:-/workspaces}
      OPEN_SWE_PROJECT_PATH: ${OPEN_SWE_PROJECT_PATH:-}
      LOCAL_SANDBOX_IMAGE: ${LOCAL_SANDBOX_IMAGE:-ghcr.io/langchain-ai/open-swe/sandbox:latest}
      LOCAL_SANDBOX_MEMORY: ${LOCAL_SANDBOX_MEMORY:-}
      LOCAL_SANDBOX_CPUS: ${LOCAL_SANDBOX_CPUS:-}
      LOCAL_SANDBOX_NETWORK: ${LOCAL_SANDBOX_NETWORK:-}
      LOCAL_SANDBOX_TIMEOUT_SEC: ${LOCAL_SANDBOX_TIMEOUT_SEC:-}
      GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME:-}
      GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL:-}
      GIT_COMMITTER_NAME: ${GIT_COMMITTER_NAME:-}
      GIT_COMMITTER_EMAIL: ${GIT_COMMITTER_EMAIL:-}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY:-}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT:-}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-}
      AZURE_OPENAI_DEPLOYMENT: ${AZURE_OPENAI_DEPLOYMENT:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      SANDBOX_ROOT_DIR: ${SANDBOX_ROOT_DIR:-}
    volumes:
      - ${WORKSPACES_ROOT:-.}:/workspaces:delegated
      - /var/run/docker.sock:/var/run/docker.sock
  ui:
    build: *openswe-build
    image: open-swe:local
    command: ["yarn", "workspace", "@openswe/web", "dev"]
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      OPEN_SWE_AGENT_BASE_URL: ${OPEN_SWE_AGENT_BASE_URL:-http://agent:2024}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY:-}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT:-}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-}
      AZURE_OPENAI_DEPLOYMENT: ${AZURE_OPENAI_DEPLOYMENT:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
    depends_on:
      - agent
volumes: {}
