services:
  sandbox-image:
    image: ${LOCAL_SANDBOX_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    profiles: ["dontstart"]

  agent:
    pull_policy: never
    environment:
      - LOCAL_SANDBOX_IMAGE=${LOCAL_SANDBOX_IMAGE}
      - WORKSPACES_ROOT=${WORKSPACES_ROOT}
    user: "${SANDBOX_UID}:${SANDBOX_GID}"
    volumes:
      - ${WORKSPACES_ROOT}:/workspaces:rw

  backend:
    pull_policy: never
    environment:
      - WORKSPACES_ROOT=${WORKSPACES_ROOT}
    volumes:
      - ${WORKSPACES_ROOT}:/workspaces:rw

  ui:
    pull_policy: never
    environment:
      - WORKSPACES_ROOT=${WORKSPACES_ROOT}
    volumes:
      - ${WORKSPACES_ROOT}:/workspaces:rw
