x-open-swe-build: &openswe-build
  context: .
  dockerfile: Dockerfile

services:
  agent:
    build: *openswe-build
    image: open-swe:local
    command: ["yarn", "workspace", "@openswe/agent", "dev"]
    environment:
      - NODE_ENV=production
    ports:
      - "2024:2024"

  web:
    build: *openswe-build
    image: open-swe:local
    command: ["yarn", "workspace", "@openswe/web", "start"]
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - agent
